language: go
go_import_path: github.com/ethereum/go-ethereum
sudo: false
matrix:
  include:
  - os: linux
    dist: xenial
    go: 1.13.x
    branches:
      only:
      - /test-bootnode-availability\/.*/
    script:
    - make test-bootnode-availability
  - os: linux
    dist: xenial
    go: 1.13.x
    branches:
      except:
        - /test-bootnode-availability\/.*/
    script:
    - go run build/ci.go install
    - travis_wait 60 go run build/ci.go test
    - make test-multigeth
    before_deploy:
    - sh build/deploy.sh
    deploy:
      provider: releases
      api_key:
        secure: f5ewX8iaY8E63wEGtLPZ8JF0/KUssJgAE+lqS7Nx5XxAM/GuE5X7mb9FmOiSzYyOexiftG8pwY0HVSXAaNk6HEl1GqlVsqMfuZgrVOAs8e0ltWgseI2T9qDp/oxxwWQ8cnPS3GrLwYUQTE+XfphL9aKkvt2RhoMmd1FPy6Dp0AYxzfLiZWCucBrR7HyHlIUjuM/DdN5U5te2loGhCyrDaKNeiIHQYp7h99cXFhKgC2N1mvXdIE7jxfiJGyEbmNksO0OY4RqBMNl7unOr8DvFf9dQBUc9cWfSRcAxt2DK4+zamX/0HJYfYRJR2Y2+z1oHrbJQnZm+9ZnOaXJt7bdWvON8jLJS+PLZT0kcSklSkKy3WEulijaGn1SIzEesadhnyHZxeDFgMnjVkSOCS0pDNtIv0SxfayqXvbYHzJhRDC4uVTRb+/PxMtZxIPCYBxLHJF6bkwmEWELl5I7UavN+jxuhkMDatqfN4V/j7JfqrLYFLHT9ByE5IBznizvJdxwXg8eo/RDJIJUwHjmKwsX9XBYmEX/UGe1O8ujJNTmg3acX9ECbwM2zgs1Br5WZtjRRDHT+YY6CbP2kPOCkpGqxwM0HPOJN/wALNVeeyCUAw3p/9mNbzJhqA8wCPmgnkzi+4m1HQoF3ADy15gUFEiq914o4dv2eQjUbgs0MaHskhEc=
      file: core-geth*-$TRAVIS_OS_NAME.*
      file_glob: true
      draft: true
      on:
        repo: etclabscore/core-geth
        tags: true
      skip_cleanup: true
      tag_name: "$TRAVIS_TAG"
  - os: linux
    dist: xenial
    sudo: required
    go: 1.13.x
    branches:
      except:
        - /test-bootnode-availability\/.*/
    env:
      - ARMv5
    git:
      submodules: false # avoid cloning ethereum/tests
    addons:
      apt:
        packages:
          - gcc-multilib
    script:
      # Switch over GCC to cross compilation (breaks 386, hence why do it here only)
      - sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install gcc-arm-linux-gnueabi libc6-dev-armel-cross gcc-arm-linux-gnueabihf libc6-dev-armhf-cross gcc-aarch64-linux-gnu libc6-dev-arm64-cross
      - sudo ln -s /usr/include/asm-generic /usr/include/asm
      - GOPATH=~/go_arm GOARM=5 go run build/ci.go install -arch arm -cc arm-linux-gnueabi-gcc
    before_deploy:
      - sh build/deploy_arm.sh
    deploy:
      provider: releases
      api_key:
        secure: f5ewX8iaY8E63wEGtLPZ8JF0/KUssJgAE+lqS7Nx5XxAM/GuE5X7mb9FmOiSzYyOexiftG8pwY0HVSXAaNk6HEl1GqlVsqMfuZgrVOAs8e0ltWgseI2T9qDp/oxxwWQ8cnPS3GrLwYUQTE+XfphL9aKkvt2RhoMmd1FPy6Dp0AYxzfLiZWCucBrR7HyHlIUjuM/DdN5U5te2loGhCyrDaKNeiIHQYp7h99cXFhKgC2N1mvXdIE7jxfiJGyEbmNksO0OY4RqBMNl7unOr8DvFf9dQBUc9cWfSRcAxt2DK4+zamX/0HJYfYRJR2Y2+z1oHrbJQnZm+9ZnOaXJt7bdWvON8jLJS+PLZT0kcSklSkKy3WEulijaGn1SIzEesadhnyHZxeDFgMnjVkSOCS0pDNtIv0SxfayqXvbYHzJhRDC4uVTRb+/PxMtZxIPCYBxLHJF6bkwmEWELl5I7UavN+jxuhkMDatqfN4V/j7JfqrLYFLHT9ByE5IBznizvJdxwXg8eo/RDJIJUwHjmKwsX9XBYmEX/UGe1O8ujJNTmg3acX9ECbwM2zgs1Br5WZtjRRDHT+YY6CbP2kPOCkpGqxwM0HPOJN/wALNVeeyCUAw3p/9mNbzJhqA8wCPmgnkzi+4m1HQoF3ADy15gUFEiq914o4dv2eQjUbgs0MaHskhEc=
      file: core-geth*-arm.*
      file_glob: true
      draft: true
      on:
        repo: etclabscore/core-geth
        tags: true
      skip_cleanup: true
      tag_name: "$TRAVIS_TAG"
  - os: osx
    go: 1.13.x
    branches:
      except:
        - /test-bootnode-availability\/.*/
    script:
    - echo "Increase the maximum number of open file descriptors on macOS"
    - NOFILE=20480
    - sudo sysctl -w kern.maxfiles=$NOFILE
    - sudo sysctl -w kern.maxfilesperproc=$NOFILE
    - sudo launchctl limit maxfiles $NOFILE $NOFILE
    - sudo launchctl limit maxfiles
    - ulimit -S -n $NOFILE
    - ulimit -n
    - unset -f cd
    - go run build/ci.go install
    before_deploy:
    - sh build/deploy.sh
    deploy:
      provider: releases
      api_key:
        secure: f5ewX8iaY8E63wEGtLPZ8JF0/KUssJgAE+lqS7Nx5XxAM/GuE5X7mb9FmOiSzYyOexiftG8pwY0HVSXAaNk6HEl1GqlVsqMfuZgrVOAs8e0ltWgseI2T9qDp/oxxwWQ8cnPS3GrLwYUQTE+XfphL9aKkvt2RhoMmd1FPy6Dp0AYxzfLiZWCucBrR7HyHlIUjuM/DdN5U5te2loGhCyrDaKNeiIHQYp7h99cXFhKgC2N1mvXdIE7jxfiJGyEbmNksO0OY4RqBMNl7unOr8DvFf9dQBUc9cWfSRcAxt2DK4+zamX/0HJYfYRJR2Y2+z1oHrbJQnZm+9ZnOaXJt7bdWvON8jLJS+PLZT0kcSklSkKy3WEulijaGn1SIzEesadhnyHZxeDFgMnjVkSOCS0pDNtIv0SxfayqXvbYHzJhRDC4uVTRb+/PxMtZxIPCYBxLHJF6bkwmEWELl5I7UavN+jxuhkMDatqfN4V/j7JfqrLYFLHT9ByE5IBznizvJdxwXg8eo/RDJIJUwHjmKwsX9XBYmEX/UGe1O8ujJNTmg3acX9ECbwM2zgs1Br5WZtjRRDHT+YY6CbP2kPOCkpGqxwM0HPOJN/wALNVeeyCUAw3p/9mNbzJhqA8wCPmgnkzi+4m1HQoF3ADy15gUFEiq914o4dv2eQjUbgs0MaHskhEc=
      file: core-geth*-$TRAVIS_OS_NAME.*
      file_glob: true
      draft: true
      on:
        repo: etclabscore/core-geth
        tags: true
      skip_cleanup: true
      tag_name: "$TRAVIS_TAG"
  - os: linux
    dist: xenial
    go: 1.13.x
    env:
    - lint
    git:
      submodules: false
    script:
    - go run build/ci.go lint
